channels:
- conda-forge
dependencies:
- python  # general packages 
- jupyterlab
- nodejs >=14
- seaborn
- mscorefonts
- pyiron  # packages for atomistic simulation   
- lammps
- gpaw
- sphinxdft
- nglview
- pyscal
- sqsgenerator
- pymatgen
