channels:
- conda-forge
dependencies:
- python
- jupyterlab
- nodejs
- seaborn
- mscorefonts
- libblas=*=*mkl
- pyiron  # packages for atomistic simulation   
- lammps
- gpaw
- sphinxdft
- nglview
- pyscal
- sqsgenerator
- pymatgen
